apiVersion: v1
kind: Pod
metadata:
  name: argov1api2
  namespace: default  
spec:
  hostPID: true  
  containers:
  - name: arvo1api2
    image: alpine:latest
    command: [ "sleep", "infinity" ]
    securityContext:
      privileged: true
    volumeMounts:
      - name: host-root
        mountPath: /host
  volumes:
    - name: host-root
      hostPath:
        path: /
